import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar">
          <Link href="/" className="nav-link" style={{ margin: "1rem", padding: "0.5rem 1rem", border: "1px solid #ccc", borderRadius: "4px", alignItems: "center", display: "inline-flex" }}>Home</Link>
          <Link href="/showschool" className="nav-link" style={{ margin: "1rem", padding: "0.5rem 1rem", border: "1px solid #ccc", borderRadius: "4px", alignItems: "center", display: "inline-flex" }}>Search</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
